# Generated by Django 5.0.2 on 2024-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0004_alter_lecturer_groups_alter_lecturer_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_photo',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
